apiVersion: v1
kind: Pod
metadata:
  name: memory-demo-pod-2
spec:
  containers:
  - name: memory-demo-container-2
    image: polinux/stress
    resources:
      limits:
        memory: "100Mi"
      requests:
        memory: "50Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
